name: geqie

volumes:
  dbdata:
  redisdata:
  miniodata:


services:
  web:
    build:
      context: ..
      dockerfile: gui/Dockerfile
    image: geqie-app:web
    env_file: .env
    environment:
      DJANGO_ASGI: "1"
      UVICORN_LIFESPAN: "off"
      PYTHONPATH: /app/gui
    command: ["/app/entrypoint.sh"]
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - minio

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432"
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "5555:80"
    restart: unless-stopped
    depends_on:
      - db


  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    restart: unless-stopped


  minio-setup:
    image: minio/mc:latest
    # One shell script as entrypoint; 'command:' doesn't work`
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e

        echo "Configuring mc alias..."
        # Temporarily disable 'exit on error' so we can loop on failures
        set +e
        until mc alias set geqie_minio http://minio:9000 "$S3_ACCESS_KEY" "$S3_SECRET_KEY"; do
          sleep 1
        done
        set -e

        echo "Creating bucket \"$S3_BUCKET\" if it does not exist..."
        mc mb --ignore-existing "geqie_minio/$S3_BUCKET"

        echo "Bucket setup done."
    restart: "no"
    depends_on:
      - minio


  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    ports:
      - "6379"
    restart: unless-stopped


  worker:
    environment:
      PYTHONPATH: /app/gui
    image: geqie-app:web
    env_file:
      - .env
    working_dir: /app
    command: >
      sh -lc '
        set -e
        echo "===> Waiting for redis ${REDIS_HOST:-redis}:6379 ..."
        for i in $(seq 1 60); do
          (echo > /dev/tcp/${REDIS_HOST:-redis}/6379) >/dev/null 2>&1 && break
          sleep 1
        done
        echo "===> Waiting for db ${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432} ..."
        for i in $(seq 1 60); do
          (echo > /dev/tcp/${POSTGRES_HOST:-db}/${POSTGRES_PORT:-5432}) >/dev/null 2>&1 && break
          sleep 1
        done
        exec celery -A gui worker -l info -Q processing_queue
      '
    restart: unless-stopped
    depends_on:
      - redis
      - db
