name: geqie

volumes:
  dbdata:
  redisdata:
  miniodata:


services:
  web:
    container_name: web
    build:
      context: ..
      dockerfile: gui/Dockerfile
    image: geqie-app:latest
    env_file: .env
    environment:
      DJANGO_ASGI: "1"
      UVICORN_LIFESPAN: "off"
      PYTHONPATH: /app/gui
    command: ["/app/entrypoint.sh"]
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - minio


  web-dev:
    container_name: web-dev
    build:
      context: ..
      dockerfile: gui/Dockerfile
    image: geqie-app:latest
    env_file: .env
    environment:
      PYTHONPATH: /app/gui
      DEV_MODE: "1"
    command: ["gunicorn", "gui.wsgi:application", "--bind", "0.0.0.0:8000", "--reload"]
    ports:
      - "8000:8000"
    restart: unless-stopped
    # volumes:
    #   - ./gui:/app
    depends_on:
      - db
      - redis
      - minio


  worker:
    container_name: worker
    image: geqie-app:latest
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/gui
    working_dir: /app
    command: >
      sh -lc '
        set -e
        exec celery -A gui worker -l info -Q processing_queue
      '
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy


  worker-dev:
    container_name: worker-dev
    image: geqie-app:latest
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/gui
      DEV_MODE: "1"
    working_dir: /app
    command: >
      sh -lc '
        set -e
        exec celery -A gui worker -l info -Q processing_queue
      '
    restart: unless-stopped
    # volumes:
    #   - ../gui:/app
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy


  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "5555:80"
    restart: unless-stopped
    depends_on:
      - db


  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    restart: unless-stopped


  minio-setup:
    container_name: minio-setup
    image: minio/mc:latest
    # One shell script as entrypoint; 'command:' doesn't work`
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e

        echo "Configuring mc alias..."
        # Temporarily disable 'exit on error' so we can loop on failures
        set +e
        until mc alias set geqie_minio http://minio:9000 "$S3_ACCESS_KEY" "$S3_SECRET_KEY"; do
          sleep 1
        done
        set -e

        echo "Creating bucket \"$S3_BUCKET\" if it does not exist..."
        mc mb --ignore-existing "geqie_minio/$S3_BUCKET"

        echo "Bucket setup done."
    restart: "no"
    depends_on:
      - minio


  redis:
    container_name: redis
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    ports:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
